# Following references have been used:
# 1) Material available in the Udacity classroom exercises 
# 2) Official documentation for GitHub Action:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# Workflow name
name: backend-ci-workflow

# Triggers 
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    types:
      - closed
    branches:
      - main

# Jobs in the workflow: linting, testing and build
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install flake8
        run: pip install flake8

      - name: Install dependencies
        run: cd backend && pipenv install

      - name: Run the linter
        run: cd backend && pipenv run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install pipenv
        run: pip install pipenv --user      

      - name: Install dependencies
        run: cd backend && pipenv install

      - name: Run tests
        run: cd backend && pipenv run test

  build:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
  
      - name: Install pipenv
        run: pip install pipenv --user

      - name: Install dependencies
        run: cd backend && pipenv install

      - name: Build docker image
        run: cd backend && docker build --tag mp-backend:latest .
        
      - name: Run docker container
        run: cd backend && docker run -p 5000:5000 --name mp-backend -d mp-backend



 